// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2TVN6hVbJ4Le0wZpPQ3Y6L0KVj_FYc70',
    appId: '1:629116131374:web:8f546d6e4e207dab44a7bf',
    messagingSenderId: '629116131374',
    projectId: 'cazziopia-demo',
    authDomain: 'cazziopia-demo.firebaseapp.com',
    storageBucket: 'cazziopia-demo.appspot.com',
    measurementId: 'G-9B0NMBLC12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6sXkZANM-AuDC-9u8cWKnH8KN_3Ovr9k',
    appId: '1:629116131374:android:544ff1184033913044a7bf',
    messagingSenderId: '629116131374',
    projectId: 'cazziopia-demo',
    storageBucket: 'cazziopia-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYkKt4T8tCRA-XxZcN12mCiWaHtc13AEM',
    appId: '1:629116131374:ios:a6e1a440f548817844a7bf',
    messagingSenderId: '629116131374',
    projectId: 'cazziopia-demo',
    storageBucket: 'cazziopia-demo.appspot.com',
    iosBundleId: 'com.example.invoiceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYkKt4T8tCRA-XxZcN12mCiWaHtc13AEM',
    appId: '1:629116131374:ios:83d398e8a336578344a7bf',
    messagingSenderId: '629116131374',
    projectId: 'cazziopia-demo',
    storageBucket: 'cazziopia-demo.appspot.com',
    iosBundleId: 'com.example.invoiceApp.RunnerTests',
  );
}
